osx_image: xcode9.2
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
# before_script:

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project TMSwiftUtilities.xcodeproj -scheme TMSwiftUtilities-Package -sdk iphonesimulator11.2 -destination 'platform=iOS Simulator,name=iPhone X,OS=11.2' ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
